// Code generated by dagger-compiler.  Do not edit.
package com.gitblit.servlet;


import dagger.internal.Binding;
import dagger.internal.Linker;
import java.util.Set;
import javax.inject.Provider;

/**
 * A {@code Binder<BranchGraphServlet>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 * 
 * Owning the dependency links between {@code BranchGraphServlet} and its
 * dependencies.
 * 
 * Being a {@code Provider<BranchGraphServlet>} and handling creation and
 * preparation of object instances.
 */
public final class BranchGraphServlet$$InjectAdapter extends Binding<BranchGraphServlet>
    implements Provider<BranchGraphServlet> {
  private Binding<com.gitblit.manager.IRuntimeManager> runtimeManager;
  private Binding<com.gitblit.manager.IRepositoryManager> repositoryManager;

  public BranchGraphServlet$$InjectAdapter() {
    super("com.gitblit.servlet.BranchGraphServlet", "members/com.gitblit.servlet.BranchGraphServlet", IS_SINGLETON, BranchGraphServlet.class);
  }

  /**
   * Used internally to link bindings/providers together at run time
   * according to their dependency graph.
   */
  @Override
  @SuppressWarnings("unchecked")
  public void attach(Linker linker) {
    runtimeManager = (Binding<com.gitblit.manager.IRuntimeManager>) linker.requestBinding("com.gitblit.manager.IRuntimeManager", BranchGraphServlet.class, getClass().getClassLoader());
    repositoryManager = (Binding<com.gitblit.manager.IRepositoryManager>) linker.requestBinding("com.gitblit.manager.IRepositoryManager", BranchGraphServlet.class, getClass().getClassLoader());
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getDependencies(Set<Binding<?>> getBindings, Set<Binding<?>> injectMembersBindings) {
    getBindings.add(runtimeManager);
    getBindings.add(repositoryManager);
  }

  /**
   * Returns the fully provisioned instance satisfying the contract for
   * {@code Provider<BranchGraphServlet>}.
   */
  @Override
  public BranchGraphServlet get() {
    BranchGraphServlet result = new BranchGraphServlet(runtimeManager.get(), repositoryManager.get());
    return result;
  }
}
