// Code generated by dagger-compiler.  Do not edit.
package com.gitblit.servlet;


import dagger.MembersInjector;
import dagger.internal.Binding;
import dagger.internal.Linker;
import java.util.Set;
import javax.inject.Provider;

/**
 * A {@code Binder<FederationServlet>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 * 
 * Owning the dependency links between {@code FederationServlet} and its
 * dependencies.
 * 
 * Being a {@code Provider<FederationServlet>} and handling creation and
 * preparation of object instances.
 * 
 * Being a {@code MembersInjector<FederationServlet>} and handling injection
 * of annotated fields.
 */
public final class FederationServlet$$InjectAdapter extends Binding<FederationServlet>
    implements Provider<FederationServlet>, MembersInjector<FederationServlet> {
  private Binding<com.gitblit.manager.IRuntimeManager> runtimeManager;
  private Binding<com.gitblit.manager.IUserManager> userManager;
  private Binding<com.gitblit.manager.IRepositoryManager> repositoryManager;
  private Binding<com.gitblit.manager.IFederationManager> federationManager;
  private Binding<JsonServlet> supertype;

  public FederationServlet$$InjectAdapter() {
    super("com.gitblit.servlet.FederationServlet", "members/com.gitblit.servlet.FederationServlet", IS_SINGLETON, FederationServlet.class);
  }

  /**
   * Used internally to link bindings/providers together at run time
   * according to their dependency graph.
   */
  @Override
  @SuppressWarnings("unchecked")
  public void attach(Linker linker) {
    runtimeManager = (Binding<com.gitblit.manager.IRuntimeManager>) linker.requestBinding("com.gitblit.manager.IRuntimeManager", FederationServlet.class, getClass().getClassLoader());
    userManager = (Binding<com.gitblit.manager.IUserManager>) linker.requestBinding("com.gitblit.manager.IUserManager", FederationServlet.class, getClass().getClassLoader());
    repositoryManager = (Binding<com.gitblit.manager.IRepositoryManager>) linker.requestBinding("com.gitblit.manager.IRepositoryManager", FederationServlet.class, getClass().getClassLoader());
    federationManager = (Binding<com.gitblit.manager.IFederationManager>) linker.requestBinding("com.gitblit.manager.IFederationManager", FederationServlet.class, getClass().getClassLoader());
    supertype = (Binding<JsonServlet>) linker.requestBinding("members/com.gitblit.servlet.JsonServlet", FederationServlet.class, getClass().getClassLoader(), false, true);
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getDependencies(Set<Binding<?>> getBindings, Set<Binding<?>> injectMembersBindings) {
    getBindings.add(runtimeManager);
    getBindings.add(userManager);
    getBindings.add(repositoryManager);
    getBindings.add(federationManager);
    injectMembersBindings.add(supertype);
  }

  /**
   * Returns the fully provisioned instance satisfying the contract for
   * {@code Provider<FederationServlet>}.
   */
  @Override
  public FederationServlet get() {
    FederationServlet result = new FederationServlet(runtimeManager.get(), userManager.get(), repositoryManager.get(), federationManager.get());
    injectMembers(result);
    return result;
  }

  /**
   * Injects any {@code @Inject} annotated fields in the given instance,
   * satisfying the contract for {@code Provider<FederationServlet>}.
   */
  @Override
  public void injectMembers(FederationServlet object) {
    supertype.injectMembers(object);
  }
}
