// Code generated by dagger-compiler.  Do not edit.
package com.gitblit.servlet;


import dagger.internal.Binding;
import dagger.internal.Linker;
import java.util.Set;
import javax.inject.Provider;

/**
 * A {@code Binder<LogoServlet>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 * 
 * Owning the dependency links between {@code LogoServlet} and its
 * dependencies.
 * 
 * Being a {@code Provider<LogoServlet>} and handling creation and
 * preparation of object instances.
 */
public final class LogoServlet$$InjectAdapter extends Binding<LogoServlet>
    implements Provider<LogoServlet> {
  private Binding<com.gitblit.manager.IRuntimeManager> runtimeManager;

  public LogoServlet$$InjectAdapter() {
    super("com.gitblit.servlet.LogoServlet", "members/com.gitblit.servlet.LogoServlet", IS_SINGLETON, LogoServlet.class);
  }

  /**
   * Used internally to link bindings/providers together at run time
   * according to their dependency graph.
   */
  @Override
  @SuppressWarnings("unchecked")
  public void attach(Linker linker) {
    runtimeManager = (Binding<com.gitblit.manager.IRuntimeManager>) linker.requestBinding("com.gitblit.manager.IRuntimeManager", LogoServlet.class, getClass().getClassLoader());
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getDependencies(Set<Binding<?>> getBindings, Set<Binding<?>> injectMembersBindings) {
    getBindings.add(runtimeManager);
  }

  /**
   * Returns the fully provisioned instance satisfying the contract for
   * {@code Provider<LogoServlet>}.
   */
  @Override
  public LogoServlet get() {
    LogoServlet result = new LogoServlet(runtimeManager.get());
    return result;
  }
}
