// Code generated by dagger-compiler.  Do not edit.
package com.gitblit.servlet;


import dagger.internal.Binding;
import dagger.internal.Linker;
import java.util.Set;
import javax.inject.Provider;

/**
 * A {@code Binder<PagesServlet>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 * 
 * Owning the dependency links between {@code PagesServlet} and its
 * dependencies.
 * 
 * Being a {@code Provider<PagesServlet>} and handling creation and
 * preparation of object instances.
 */
public final class PagesServlet$$InjectAdapter extends Binding<PagesServlet>
    implements Provider<PagesServlet> {
  private Binding<com.gitblit.manager.IRuntimeManager> runtimeManager;
  private Binding<com.gitblit.manager.IRepositoryManager> repositoryManager;

  public PagesServlet$$InjectAdapter() {
    super("com.gitblit.servlet.PagesServlet", "members/com.gitblit.servlet.PagesServlet", IS_SINGLETON, PagesServlet.class);
  }

  /**
   * Used internally to link bindings/providers together at run time
   * according to their dependency graph.
   */
  @Override
  @SuppressWarnings("unchecked")
  public void attach(Linker linker) {
    runtimeManager = (Binding<com.gitblit.manager.IRuntimeManager>) linker.requestBinding("com.gitblit.manager.IRuntimeManager", PagesServlet.class, getClass().getClassLoader());
    repositoryManager = (Binding<com.gitblit.manager.IRepositoryManager>) linker.requestBinding("com.gitblit.manager.IRepositoryManager", PagesServlet.class, getClass().getClassLoader());
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getDependencies(Set<Binding<?>> getBindings, Set<Binding<?>> injectMembersBindings) {
    getBindings.add(runtimeManager);
    getBindings.add(repositoryManager);
  }

  /**
   * Returns the fully provisioned instance satisfying the contract for
   * {@code Provider<PagesServlet>}.
   */
  @Override
  public PagesServlet get() {
    PagesServlet result = new PagesServlet(runtimeManager.get(), repositoryManager.get());
    return result;
  }
}
