// Code generated by dagger-compiler.  Do not edit.
package com.gitblit.servlet;


import dagger.MembersInjector;
import dagger.internal.Binding;
import dagger.internal.Linker;
import java.util.Set;
import javax.inject.Provider;

/**
 * A {@code Binder<RpcFilter>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 * 
 * Owning the dependency links between {@code RpcFilter} and its
 * dependencies.
 * 
 * Being a {@code Provider<RpcFilter>} and handling creation and
 * preparation of object instances.
 * 
 * Being a {@code MembersInjector<RpcFilter>} and handling injection
 * of annotated fields.
 */
public final class RpcFilter$$InjectAdapter extends Binding<RpcFilter>
    implements Provider<RpcFilter>, MembersInjector<RpcFilter> {
  private Binding<com.gitblit.manager.IRuntimeManager> runtimeManager;
  private Binding<com.gitblit.manager.IAuthenticationManager> authenticationManager;
  private Binding<AuthenticationFilter> supertype;

  public RpcFilter$$InjectAdapter() {
    super("com.gitblit.servlet.RpcFilter", "members/com.gitblit.servlet.RpcFilter", IS_SINGLETON, RpcFilter.class);
  }

  /**
   * Used internally to link bindings/providers together at run time
   * according to their dependency graph.
   */
  @Override
  @SuppressWarnings("unchecked")
  public void attach(Linker linker) {
    runtimeManager = (Binding<com.gitblit.manager.IRuntimeManager>) linker.requestBinding("com.gitblit.manager.IRuntimeManager", RpcFilter.class, getClass().getClassLoader());
    authenticationManager = (Binding<com.gitblit.manager.IAuthenticationManager>) linker.requestBinding("com.gitblit.manager.IAuthenticationManager", RpcFilter.class, getClass().getClassLoader());
    supertype = (Binding<AuthenticationFilter>) linker.requestBinding("members/com.gitblit.servlet.AuthenticationFilter", RpcFilter.class, getClass().getClassLoader(), false, true);
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getDependencies(Set<Binding<?>> getBindings, Set<Binding<?>> injectMembersBindings) {
    getBindings.add(runtimeManager);
    getBindings.add(authenticationManager);
    injectMembersBindings.add(supertype);
  }

  /**
   * Returns the fully provisioned instance satisfying the contract for
   * {@code Provider<RpcFilter>}.
   */
  @Override
  public RpcFilter get() {
    RpcFilter result = new RpcFilter(runtimeManager.get(), authenticationManager.get());
    injectMembers(result);
    return result;
  }

  /**
   * Injects any {@code @Inject} annotated fields in the given instance,
   * satisfying the contract for {@code Provider<RpcFilter>}.
   */
  @Override
  public void injectMembers(RpcFilter object) {
    supertype.injectMembers(object);
  }
}
