// Code generated by dagger-compiler.  Do not edit.
package com.gitblit.servlet;


import dagger.MembersInjector;
import dagger.internal.Binding;
import dagger.internal.Linker;
import java.util.Set;
import javax.inject.Provider;

/**
 * A {@code Binder<RpcServlet>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 * 
 * Owning the dependency links between {@code RpcServlet} and its
 * dependencies.
 * 
 * Being a {@code Provider<RpcServlet>} and handling creation and
 * preparation of object instances.
 * 
 * Being a {@code MembersInjector<RpcServlet>} and handling injection
 * of annotated fields.
 */
public final class RpcServlet$$InjectAdapter extends Binding<RpcServlet>
    implements Provider<RpcServlet>, MembersInjector<RpcServlet> {
  private Binding<com.gitblit.manager.IGitblit> gitblit;
  private Binding<JsonServlet> supertype;

  public RpcServlet$$InjectAdapter() {
    super("com.gitblit.servlet.RpcServlet", "members/com.gitblit.servlet.RpcServlet", IS_SINGLETON, RpcServlet.class);
  }

  /**
   * Used internally to link bindings/providers together at run time
   * according to their dependency graph.
   */
  @Override
  @SuppressWarnings("unchecked")
  public void attach(Linker linker) {
    gitblit = (Binding<com.gitblit.manager.IGitblit>) linker.requestBinding("com.gitblit.manager.IGitblit", RpcServlet.class, getClass().getClassLoader());
    supertype = (Binding<JsonServlet>) linker.requestBinding("members/com.gitblit.servlet.JsonServlet", RpcServlet.class, getClass().getClassLoader(), false, true);
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getDependencies(Set<Binding<?>> getBindings, Set<Binding<?>> injectMembersBindings) {
    getBindings.add(gitblit);
    injectMembersBindings.add(supertype);
  }

  /**
   * Returns the fully provisioned instance satisfying the contract for
   * {@code Provider<RpcServlet>}.
   */
  @Override
  public RpcServlet get() {
    RpcServlet result = new RpcServlet(gitblit.get());
    injectMembers(result);
    return result;
  }

  /**
   * Injects any {@code @Inject} annotated fields in the given instance,
   * satisfying the contract for {@code Provider<RpcServlet>}.
   */
  @Override
  public void injectMembers(RpcServlet object) {
    supertype.injectMembers(object);
  }
}
