// Code generated by dagger-compiler.  Do not edit.
package com.gitblit.servlet;


import dagger.MembersInjector;
import dagger.internal.Binding;
import dagger.internal.Linker;
import java.util.Set;
import javax.inject.Provider;

/**
 * A {@code Binder<SyndicationFilter>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 * 
 * Owning the dependency links between {@code SyndicationFilter} and its
 * dependencies.
 * 
 * Being a {@code Provider<SyndicationFilter>} and handling creation and
 * preparation of object instances.
 * 
 * Being a {@code MembersInjector<SyndicationFilter>} and handling injection
 * of annotated fields.
 */
public final class SyndicationFilter$$InjectAdapter extends Binding<SyndicationFilter>
    implements Provider<SyndicationFilter>, MembersInjector<SyndicationFilter> {
  private Binding<com.gitblit.manager.IRuntimeManager> runtimeManager;
  private Binding<com.gitblit.manager.IAuthenticationManager> authenticationManager;
  private Binding<com.gitblit.manager.IRepositoryManager> repositoryManager;
  private Binding<com.gitblit.manager.IProjectManager> projectManager;
  private Binding<AuthenticationFilter> supertype;

  public SyndicationFilter$$InjectAdapter() {
    super("com.gitblit.servlet.SyndicationFilter", "members/com.gitblit.servlet.SyndicationFilter", IS_SINGLETON, SyndicationFilter.class);
  }

  /**
   * Used internally to link bindings/providers together at run time
   * according to their dependency graph.
   */
  @Override
  @SuppressWarnings("unchecked")
  public void attach(Linker linker) {
    runtimeManager = (Binding<com.gitblit.manager.IRuntimeManager>) linker.requestBinding("com.gitblit.manager.IRuntimeManager", SyndicationFilter.class, getClass().getClassLoader());
    authenticationManager = (Binding<com.gitblit.manager.IAuthenticationManager>) linker.requestBinding("com.gitblit.manager.IAuthenticationManager", SyndicationFilter.class, getClass().getClassLoader());
    repositoryManager = (Binding<com.gitblit.manager.IRepositoryManager>) linker.requestBinding("com.gitblit.manager.IRepositoryManager", SyndicationFilter.class, getClass().getClassLoader());
    projectManager = (Binding<com.gitblit.manager.IProjectManager>) linker.requestBinding("com.gitblit.manager.IProjectManager", SyndicationFilter.class, getClass().getClassLoader());
    supertype = (Binding<AuthenticationFilter>) linker.requestBinding("members/com.gitblit.servlet.AuthenticationFilter", SyndicationFilter.class, getClass().getClassLoader(), false, true);
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getDependencies(Set<Binding<?>> getBindings, Set<Binding<?>> injectMembersBindings) {
    getBindings.add(runtimeManager);
    getBindings.add(authenticationManager);
    getBindings.add(repositoryManager);
    getBindings.add(projectManager);
    injectMembersBindings.add(supertype);
  }

  /**
   * Returns the fully provisioned instance satisfying the contract for
   * {@code Provider<SyndicationFilter>}.
   */
  @Override
  public SyndicationFilter get() {
    SyndicationFilter result = new SyndicationFilter(runtimeManager.get(), authenticationManager.get(), repositoryManager.get(), projectManager.get());
    injectMembers(result);
    return result;
  }

  /**
   * Injects any {@code @Inject} annotated fields in the given instance,
   * satisfying the contract for {@code Provider<SyndicationFilter>}.
   */
  @Override
  public void injectMembers(SyndicationFilter object) {
    supertype.injectMembers(object);
  }
}
