/* Generated By:JavaCC: Do not edit this line. JavaCCParserConstants.java */
/**
 * This file contains the code for JavaCCParser generated
 * by JavaCCParser itself.
 */

package org.javacc.parser;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JavaCCParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int _LOOKAHEAD = 1;
  /** RegularExpression Id. */
  int _IGNORE_CASE = 2;
  /** RegularExpression Id. */
  int _PARSER_BEGIN = 3;
  /** RegularExpression Id. */
  int _PARSER_END = 4;
  /** RegularExpression Id. */
  int _JAVACODE = 5;
  /** RegularExpression Id. */
  int _TOKEN = 6;
  /** RegularExpression Id. */
  int _SPECIAL_TOKEN = 7;
  /** RegularExpression Id. */
  int _MORE = 8;
  /** RegularExpression Id. */
  int _SKIP = 9;
  /** RegularExpression Id. */
  int _TOKEN_MGR_DECLS = 10;
  /** RegularExpression Id. */
  int _EOF = 11;
  /** RegularExpression Id. */
  int _DCL_PARSER_BEGIN = 12;
  /** RegularExpression Id. */
  int _DCL_PARSER_END = 13;
  /** RegularExpression Id. */
  int _INC_PARSER_BEGIN = 14;
  /** RegularExpression Id. */
  int _INC_PARSER_END = 15;
  /** RegularExpression Id. */
  int _DEF_PARSER_BEGIN = 16;
  /** RegularExpression Id. */
  int _DEF_PARSER_END = 17;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 29;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 30;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 31;
  /** RegularExpression Id. */
  int ABSTRACT = 33;
  /** RegularExpression Id. */
  int ASSERT = 34;
  /** RegularExpression Id. */
  int BOOLEAN = 35;
  /** RegularExpression Id. */
  int BREAK = 36;
  /** RegularExpression Id. */
  int BYTE = 37;
  /** RegularExpression Id. */
  int CASE = 38;
  /** RegularExpression Id. */
  int CATCH = 39;
  /** RegularExpression Id. */
  int CHAR = 40;
  /** RegularExpression Id. */
  int CLASS = 41;
  /** RegularExpression Id. */
  int CONST = 42;
  /** RegularExpression Id. */
  int CONTINUE = 43;
  /** RegularExpression Id. */
  int _DEFAULT = 44;
  /** RegularExpression Id. */
  int DO = 45;
  /** RegularExpression Id. */
  int DOUBLE = 46;
  /** RegularExpression Id. */
  int ELSE = 47;
  /** RegularExpression Id. */
  int ENUM = 48;
  /** RegularExpression Id. */
  int EXTENDS = 49;
  /** RegularExpression Id. */
  int FALSE = 50;
  /** RegularExpression Id. */
  int FINAL = 51;
  /** RegularExpression Id. */
  int FINALLY = 52;
  /** RegularExpression Id. */
  int FLOAT = 53;
  /** RegularExpression Id. */
  int FOR = 54;
  /** RegularExpression Id. */
  int GOTO = 55;
  /** RegularExpression Id. */
  int IF = 56;
  /** RegularExpression Id. */
  int IMPLEMENTS = 57;
  /** RegularExpression Id. */
  int IMPORT = 58;
  /** RegularExpression Id. */
  int INSTANCEOF = 59;
  /** RegularExpression Id. */
  int INT = 60;
  /** RegularExpression Id. */
  int INTERFACE = 61;
  /** RegularExpression Id. */
  int LONG = 62;
  /** RegularExpression Id. */
  int NATIVE = 63;
  /** RegularExpression Id. */
  int NEW = 64;
  /** RegularExpression Id. */
  int NULL = 65;
  /** RegularExpression Id. */
  int PACKAGE = 66;
  /** RegularExpression Id. */
  int PRIVATE = 67;
  /** RegularExpression Id. */
  int PROTECTED = 68;
  /** RegularExpression Id. */
  int PUBLIC = 69;
  /** RegularExpression Id. */
  int RETURN = 70;
  /** RegularExpression Id. */
  int SHORT = 71;
  /** RegularExpression Id. */
  int STATIC = 72;
  /** RegularExpression Id. */
  int STRICTFP = 73;
  /** RegularExpression Id. */
  int SUPER = 74;
  /** RegularExpression Id. */
  int SWITCH = 75;
  /** RegularExpression Id. */
  int SYNCHRONIZED = 76;
  /** RegularExpression Id. */
  int THIS = 77;
  /** RegularExpression Id. */
  int THROW = 78;
  /** RegularExpression Id. */
  int THROWS = 79;
  /** RegularExpression Id. */
  int TRANSIENT = 80;
  /** RegularExpression Id. */
  int TRUE = 81;
  /** RegularExpression Id. */
  int TRY = 82;
  /** RegularExpression Id. */
  int VOID = 83;
  /** RegularExpression Id. */
  int VOLATILE = 84;
  /** RegularExpression Id. */
  int WHILE = 85;
  /** RegularExpression Id. */
  int TEMPLATE = 86;
  /** RegularExpression Id. */
  int TYPENAME = 87;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 88;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 89;
  /** RegularExpression Id. */
  int HEX_LITERAL = 90;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 91;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 92;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 93;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 94;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 95;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 96;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 97;
  /** RegularExpression Id. */
  int STRING_LITERAL = 98;
  /** RegularExpression Id. */
  int LPAREN = 99;
  /** RegularExpression Id. */
  int RPAREN = 100;
  /** RegularExpression Id. */
  int LBRACE = 101;
  /** RegularExpression Id. */
  int RBRACE = 102;
  /** RegularExpression Id. */
  int LBRACKET = 103;
  /** RegularExpression Id. */
  int RBRACKET = 104;
  /** RegularExpression Id. */
  int SEMICOLON = 105;
  /** RegularExpression Id. */
  int COMMA = 106;
  /** RegularExpression Id. */
  int DOT = 107;
  /** RegularExpression Id. */
  int ASSIGN = 108;
  /** RegularExpression Id. */
  int LT = 109;
  /** RegularExpression Id. */
  int BANG = 110;
  /** RegularExpression Id. */
  int TILDE = 111;
  /** RegularExpression Id. */
  int HOOK = 112;
  /** RegularExpression Id. */
  int COLON = 113;
  /** RegularExpression Id. */
  int DOUBLECOLON = 114;
  /** RegularExpression Id. */
  int EQ = 115;
  /** RegularExpression Id. */
  int LE = 116;
  /** RegularExpression Id. */
  int GE = 117;
  /** RegularExpression Id. */
  int NE = 118;
  /** RegularExpression Id. */
  int SC_OR = 119;
  /** RegularExpression Id. */
  int SC_AND = 120;
  /** RegularExpression Id. */
  int INCR = 121;
  /** RegularExpression Id. */
  int DECR = 122;
  /** RegularExpression Id. */
  int PLUS = 123;
  /** RegularExpression Id. */
  int MINUS = 124;
  /** RegularExpression Id. */
  int STAR = 125;
  /** RegularExpression Id. */
  int SLASH = 126;
  /** RegularExpression Id. */
  int BIT_AND = 127;
  /** RegularExpression Id. */
  int BIT_OR = 128;
  /** RegularExpression Id. */
  int XOR = 129;
  /** RegularExpression Id. */
  int REM = 130;
  /** RegularExpression Id. */
  int PLUSASSIGN = 131;
  /** RegularExpression Id. */
  int MINUSASSIGN = 132;
  /** RegularExpression Id. */
  int STARASSIGN = 133;
  /** RegularExpression Id. */
  int SLASHASSIGN = 134;
  /** RegularExpression Id. */
  int ANDASSIGN = 135;
  /** RegularExpression Id. */
  int ORASSIGN = 136;
  /** RegularExpression Id. */
  int XORASSIGN = 137;
  /** RegularExpression Id. */
  int REMASSIGN = 138;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFT = 139;
  /** RegularExpression Id. */
  int RSIGNEDSHIFT = 140;
  /** RegularExpression Id. */
  int GT = 141;
  /** RegularExpression Id. */
  int LANGLE = 109;
  /** RegularExpression Id. */
  int RANGLE = 141;
  /** RegularExpression Id. */
  int IDENTIFIER = 149;
  /** RegularExpression Id. */
  int LETTER = 150;
  /** RegularExpression Id. */
  int PART_LETTER = 151;
  /** RegularExpression Id. */
  int ACT_TOK = 152;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int AFTER_EGEN = 1;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 2;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 3;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 4;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"LOOKAHEAD\"",
    "\"IGNORE_CASE\"",
    "\"PARSER_BEGIN\"",
    "\"PARSER_END\"",
    "\"JAVACODE\"",
    "\"TOKEN\"",
    "\"SPECIAL_TOKEN\"",
    "\"MORE\"",
    "\"SKIP\"",
    "\"TOKEN_MGR_DECLS\"",
    "\"EOF\"",
    "\"DCL_PARSER_BEGIN\"",
    "\"DCL_PARSER_END\"",
    "\"INC_PARSER_BEGIN\"",
    "\"INC_PARSER_END\"",
    "\"DEF_PARSER_BEGIN\"",
    "\"DEF_PARSER_END\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"/*@egen*/\"",
    "<token of kind 24>",
    "\"//\"",
    "<token of kind 26>",
    "\"/*\"",
    "\"/*@bgen(jjtree\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 32>",
    "\"abstract\"",
    "\"assert\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"strictfp\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"template\"",
    "\"typename\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"::\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\">>>\"",
    "\">>\"",
    "\">\"",
    "\"#\"",
    "\"...\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"<<\"",
    "\"@\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "<ACT_TOK>",
  };

}
