////////////////////////////////////////////////////////////////////////
/*
     FILE: DataTransferEvent.java
  PURPOSE: To handle data transfer events.
   AUTHOR: Peter Hollemans
     DATE: 2002/02/16
  CHANGES: 2003/10/26, PFH, added to the Coastwatch package

  CoastWatch Software Library and Utilities
  Copyright 1998-2003, USDOC/NOAA/NESDIS CoastWatch

*/
////////////////////////////////////////////////////////////////////////

// Package
// -------
//package noaa.coastwatch.io;
package gov.noaa.ncdc.common;

// Imports
// -------
import java.util.EventObject;

/**
 * A data transfer event handles the details of a data transfer.  Data
 * transfer events are generated by a <code>DataTransfer</code> object
 * to signal the start, progress, stop, and error in a data transfer
 * operation.
 */
public class DataTransferEvent
  extends EventObject {

  ////////////////////////////////////////////////////////////

  /** Create a new data transfer event. */
  public DataTransferEvent (
    Object source
  ) { 
 
    super (source);

  } // DataTransferEvent

  ////////////////////////////////////////////////////////////

} // DataTransferEvent class

////////////////////////////////////////////////////////////////////////
