/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.node;

import org.sablecc.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TStates extends Token
{
    public TStates()
    {
        super.setText("States");
    }

    public TStates(int line, int pos)
    {
        super.setText("States");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TStates(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTStates(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TStates text.");
    }
}
