/*
 * NewJFrame.java
 *
 * Created on January 15, 2008, 12:28 PM
 */

package gov.noaa.ncdc.iosp.avhrr.util;

import javax.swing.JEditorPane;

/**
 *
 * @author  afotos
 */
public class HelpFrame extends javax.swing.JFrame {

	private static String helpText = "<html>\n<body>\n<h1>NCDC AVHRR Level 1B Converter</h1>\n<a href=\"#general\">General Information</a><br/>\n<a href=\"#requirements\">Requirements</a><br/>\n<a href=\"#files\">Supported Files</a><br/>\n<a href=\"#options\">Options</a><br/>\n<a href=\"#limitations\">Limitations</a><br/>\n\n<a name=\"general\"></a>\n<H3>General Information</H3>\n<div name=\"general\">\nThis application is experimental and any output has not been fully tested.\nUse at your own risk!\n</div>\n\n<a name=\"requirements\"></a>\n<H3>Requirements</H3>\n<div name=\"requirements\">\nJava JRE 1.5 or greater is required to run this application.\nThis application should be run from a command line using the following command: java -Xmx1024M -jar sat2netcdf.jar.\nClasspath issues can result from launching the application by double-clicking the jar.\n1024M of maximum heap space is recommended.  This can be adjusted with the -Xmx runtime argument.\nIf Out of memory: heap space exceptions occur increase the maximum heap size.\n\n</div>\n\n<H3>Supported Files</H3>\n<a name=\"files\"></a>\n<div id=\"files\">\n<p>\nThis program is designed to convert Avhrr Global Area Coverage (GAC) 4KM Level 1B downloaded from CLASS to netcdf-3 format.\nCurrently, only 10 bit/pixel data format is supported. Files with or without the Archive Header are supported.\n</p>\n</div>\n<a name=\"options\">\n<H3>Options</H3>\n<div id=\"options\">\n<H4>Channels</H4>\n This option allows the user to select which channels will be included in the netcdf file.  \n\n<br/>\n<H4>Calibration</H4>\n<H5>Raw Data</H5> Count values for each pixel will be output.\n<H5>Radiance</H5> Randiance values for each pixel will be output.\n<H5>Brightness Temperature</H5> For chanels 1, 2, and 3A Albeito values for each pixel will be output.\n\tFor channels 3B, 4, and 5 Brightness Temperature values for each pixel will be output.\n\t\n<br/>\nAll Variables - This will output all variables in the dataset. This will produce a large netcdf file.\nThe final final will be approximately 10 times larger than the source file with this option selected.\n<br/>\n<br/>\nLat/Lon - This option will output the 51 anchor point lat/lon values for each scan line, and interpolated lat/lon vlaues \nfor each pixel.\n<br/>\n<br/>Metadata - This option will supply all header record variables and a majority of dataset variables, excluding\nthe variables specified by the other options.\n\n<br/>\n\n</div>\n\n<a name=\"limitations\"></a>\n<H3>Limitations</H3>\n<div id=\"limitations\">\n\n</div>\n\n</body>\n\n\n</html>";
    /** Creates new form NewJFrame */
    public HelpFrame() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	this.setTitle("HELP");
        jScrollPane1 = new javax.swing.JScrollPane();
        closeButton = new javax.swing.JButton();
		jTextArea1 = new JEditorPane("text/html",helpText);
		jTextArea1.setEditable(false);
        jScrollPane1.setViewportView(jTextArea1);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        closeButton.setLabel("Close");
        closeButton.setName("closeButton"); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jTextArea1);
        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(324, Short.MAX_VALUE)
                .add(closeButton)
                .addContainerGap())
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 262, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(closeButton)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HelpFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JScrollPane jScrollPane1;
    private JEditorPane  jTextArea1;
    
}
